### PR TITLE
Add support for multiple destinations

### PR DESCRIPTION
**Pull request by itemir**
This change adds support to send AIS messages to multiple destinations like MarineTraffic, AIS Hub etc simultaneously (#1). It also fixes the problem explained in #4.

On the flip side, since it changes how the plugin is configured, it will require existing plugin users to re-configure the destination after they upgrade.

### CODE REVIEW

**Comment by hkapanen** [comment]
Thank you for the PR! Some quick comments or questions:
1) Why dropping event listener removals on stop?
2) Wouldn't AIVDM/AIVDO test be more efficiently implemented outside the endpoint loop?

**Comment by hkapanen** [comment]
Also, could you please add some basic tests checking that ...
1) AIVDM/O message selection works as intended
2) other nmea sentences are not forwarded 
3) that this works properly with 0/1/>1 endpoints?

**Comment by itemir** [comment]
Hey, thanks. On 2, yes, I was doing this change late at night and didn't see that ;-) I just submitted a commit to change that.

On 1, I don't think dropping the event loop on stop was working. I think #4 was somehow related to that, there was something wrong with that part of the code. I didn't have the time to troubleshoot it further and get to the root-cause and I didn't think it was necessary. Closing the socket and resetting the endpoint array basically stops the plugin. Yes the listener stays if the plugin is stopped until a reset but didn't think it was a big deal. When someone has time, this warrants a further look.

On testing, yes it is working on all three scenarios. I tweaked the plugin since I submit my data to AIS Hub and Marinetraffic and I was trying to get rid of aisdispatcher and do everything via SignalK. I started using it since yesterday, and works nicely.

Thanks for the plugin!

**Comment by Ianknx** [comment]
Hi

Cant wait for this to be implemented will be following.

**Comment by hkapanen** [comment]
@itemir,

Any thoughts on how to handle the version upgrade case? The old config in the system will obviously not work and something sensible should happen.

WRT testing, I meant it would be good to add some basic standalone test code to go with the plugin on the repo. One suggestion (from @tkurki) on how to do this would be to turn the exported entry function into `function(app, sendToSocket)` and have your own socket code to assert that it's called in a proper manner when running in test mode. If sendToSocket is not defined (normal mode) then it'd use the normal socket.send.

I appreciate you working on this as I'm not a developer and I haven't had the env up in ages. And my boat is hibernating until springtime.

**Comment by Ianknx** [comment]
As a basic user with little technical know-how I feel a system such as the @signalk/aisreporter by Teppo Kukri would be an ideal set up in where  "units" can be added by ip and port information within a plug in so that it is user friendly, if I can be of any help..

**Comment by itemir** [comment]
@hkapanen Upgrade case is tough with no ideal solution. One very crappy solution would be to keep the old config setup as is and add a new config setup on top, that can accept multiple IP address, port pairs. That I think would be odd and not user friendly, also would add a small layer of unnecessary complication to the code and adds new test cases, etc. 

A second solution is just to accept the breaking change and put an explicit note to users. It is easy on the side of users and really a 10 second reconfiguration but obviously they need to know and do it, not necessarily a given.

A third solution would be to keep the old plugin as is and re-publish this as a different version. It would basically make this a different plugin though. We could call it ais-forwarder2 or aisdispatcher (aisdispatcher is the tool many people use to send their AIS data so as a reference to that). 

Your point on not being an active developer brings a potentially different complication though. However we tackle this, will you be able to re-publish the package to npmjs? It will be needed to put the plugin into signalk plugin repo. If you don't have the setup for that, I could do that but it will have to be a different version/new plugin in that scenario since I don't think I can access your account. There may be ways for that but that also goes beyond my familarity with npmjs.

On testing, Teppo writes code like a professional developer and tests the code like one! Unfortunately I am more the "get things done that are needed and move on type" :) So yes, committing test cases would be good but honestly, none of my plugins or hobby code have them, so I don't think I will be able to add them here. Let me know how big of a deal it is for you and it is good for me either way. I did this for a personal need and it is satisfying my needs. I will respect your decision as the plugin owner, you should make that call.

@Ianknx The commit we are discussing does precisely that, allowing you to add multiple "units" (see [this screenshot](https://github.com/itemir/ais-forwarder/raw/master/ais-forwarder.png) ). It will introduce a breaking change though, meaning after the upgrade, plugin will stop working unless you re-configure it. That is what we are discussing and some issues related to testing.

**Comment by tkurki** [comment]
It's a bit hacky, but you can write a bit of code that

1. detects that config is from the previous version
2. creates config object in new format with data from the previous format
3. saves the upgraded config object
4. proceeds to startup with the new config object

Sort of like this
```
    start: options => {
      if (!options.foobar ) {
        options.foobar = options.baz
        app.savePluginOptions(options, () => {})
      }
  ...
```

We really should create explicit support for plugin config version management - this is not the only plugin that is hitting this.

PS `Note: AIS data (NMEA0183) forwarder is using deprecated setProviderStatus/Error https://github.com/SignalK/signalk-server/blob/master/SERVERPLUGINS.md#appsetproviderstatusmsg`

**Comment by Ianknx** [comment]
Thanks for keeping me updated, if I can help in any way please let me know.

**Comment by hkapanen** [comment]
I don't want to publish another version and can republish the npmjs -- no worries! 

WRT discussion on features, config and tests, I'd also like to approach this from practical point of view and thus my priority order would be:
1) Functionality => multiple endpoints [done]
2) Non-breaking change => handle the config change, perhaps as suggested by Teppo above
3) Handle the setProviderStatus/Error properly
4) Tests

I can live with tests implemented "later". ;)

**Comment by itemir** [comment]
Ok, that makes sense. However, someone else needs to take it from here. I don't think I will be able to spend more time on it. I will keep the PR open and the changes can be made on it.

In the meantime, @lanknx you could try to use the 'development' version. You should follow the instructions [here](https://github.com/SignalK/signalk-server/blob/master/SERVERPLUGINS.md) to understand how to run a development plugin. 

It should look like something like this:

First remove the plugin. Note that your config will be lost, so capture it first. Then:

`$ git clone https://github.com/itemir/ais-forwarder`
`$ cd ais-forwarder`
`$ sudo npm link      # You may not need sudo, try without it first`
`$ cd ~/.signalk        # I think this is the default install location on RPi but tweak as needed`
`$ npm link ais-forwarder`

You can now restart your Signal K server and plugin version 0.3.0 should show up. You may need to tweak some of the steps above, consult the documentation I referenced as needed.

P.S @tkurki I had updated setProviderStatus in my change so that should be good.

**Comment by Ianknx** [comment]
I will give it a try today and let you know.

**Comment by Ianknx** [comment]
Jan 24 16:43:39 2021-01-24T16:43:39.618Z ais-forwarder sending to 144.76.105.244:2054: !AIVDM,1,1,,A,13M@D7@02:Or2rVM45fPN0G>0<25,0*7FJan 24 16:43:39 2021-01-24T16:43:39.620Z ais-forwarder sending to 5.9.207.224:11504: !AIVDM,1,1,,A,13M@D7@02:Or2rVM45fPN0G>0<25,0*7FJan 24 16:43:49 2021-01-24T16:43:49.938Z ais-forwarder sending to 144.76.105.244:2054: !AIVDM,1,1,,B,13M@D7@2j9Or2vJM47;@MhGR0@M<,0*4FJan 24 16:43:49 2021-01-24T16:43:49.940Z ais-forwarder sending to 5.9.207.224:11504: !AIVDM,1,1,,B,13M@D7@2j9Or2vJM47;@MhGR0@M<,0*4FJan 24 16:43:58 2021-01-24T16:43:58.865Z ais-forwarder sending to 144.76.105.244:2054: !AIVDM,1,1,,A,13M@D7@027Or31nM48M@N0Il08RL,0*7FJan 24 16:43:58 2021-01-24T16:43:58.866Z ais-forwarder sending to 5.9.207.224:11504: !AIVDM,1,1,,A,13M@D7@027Or31nM48M@N0Il08RL,0*7F   Sent from Mail for Windows 10 From: Ilker TemirSent: 24 January 2021 03:02To: hkapanen/ais-forwarderCc: Ianknx; MentionSubject: Re: [hkapanen/ais-forwarder] Add support for multiple destinations (#5) Ok, that makes sense. However, someone else needs to take it from here. I don't think I will be able to spend more time on it. I will keep the PR open and the changes can be made on it.In the meantime, @lanknx you could try to use the 'development' version. You should follow the instructions here to get a development plugin.It should look like something like this:First remove the plugin. Note that your config will be lost, so capture it first. Then:$ git clone https://github.com/itemir/ais-forwarder $ cd ais-forwarder $ sudo npm link # You may not need sudo, try without it first $ cd ~/.signalk # This is the default install location on RPi but tweak as needed $ npm link ais-forwarderYou can now restart your Signal K server and plugin version 0.3.0 should show up. You may need to tweak some of the steps above, consult the documentation I referenced above.P.S @tkurki I had updated setProviderStatus in my change so that should be good.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Ianknx** [comment]
Working perfectly, have checked that the AIS is being received at destination.

from server log:-

Jan 24 16:43:39 2021-01-24T16:43:39.618Z ais-forwarder sending to 144.76.105.244:2054: !AIVDM,1,1,,A,13M@D7@02:Or2rVM45fPN0G>0<25,0*7FJan 24 16:43:39 2021-01-24T16:43:39.620Z ais-forwarder sending to 5.9.207.224:11504: !AIVDM,1,1,,A,13M@D7@02:Or2rVM45fPN0G>0<25,0*7FJan 24 16:43:49 2021-01-24T16:43:49.938Z ais-forwarder sending to 144.76.105.244:2054: !AIVDM,1,1,,B,13M@D7@2j9Or2vJM47;@MhGR0@M<,0*4FJan 24 16:43:49 2021-01-24T16:43:49.940Z ais-forwarder sending to 5.9.207.224:11504: !AIVDM,1,1,,B,13M@D7@2j9Or2vJM47;@MhGR0@M<,0*4FJan 24 16:43:58 2021-01-24T16:43:58.865Z ais-forwarder sending to 144.76.105.244:2054: !AIVDM,1,1,,A,13M@D7@027Or31nM48M@N0Il08RL,0*7FJan 24 16:43:58 2021-01-24T16:43:58.866Z ais-forwarder sending to 5.9.207.224:11504: !AIVDM,1,1,,A,13M@D7@027Or31nM48M@N0Il08RL,0*7F

**Comment by mrinkel** [comment]
Thanks!  Works great!

**Comment by muebau** [comment]
I might have found an issue:
If one of the destinations is "bad" the transmission is stop at this point and following destinations don't get any traffic. Lets say the third destination is not reachable the fourth will get not transmission at all.

It might be some unhandled crash in some loop in the code I guess.

**Comment by muebau** [comment]
The plugin aisreporter (https://www.npmjs.com/package/@signalk/aisreporter) has a great way to add the addresses. One can add as many addresses as desired and the GUI does not need spare input fields which might look cleaner.

**Comment by itemir** [comment]
Hey @hkapanen , are you planning to do something about this? If not, I will publish this as a standalone plugin as a fork of yours.

**Comment by Ianknx** [comment]
Hello

Please go ahead, I am unaware of how to publish, it is not my "patch" I
only came up eith the idea.

Regards

Ian

**Comment by hkapanen** [comment]
Thanks for a wakeup call -- I'll now merge and publish this version with a comment that existing users need to reconfigure their setup.

**Pull request merged**
