### PR TITLE
Add option to convert AIVDO to AIVDM

### PR DESCRIPTION
**Pull request by yifswery**
Currently some AIS Aggregators dont display or support own vessel AIVDO sentence (AISHub for example)  This means  in order to make sure they see and display our vessel we need to convert AIVDO -> AIVDM.  This additional options does exactly that.

### CODE REVIEW

**Comment by hkapanen** [comment]
Thanks @yifswery! Some questions:
1) Have you tested this?
2) Could you update the image accordingly, please?
3) How about having forward and conversion options per endpoint?

**Comment by yifswery** [comment]
@hkapanen 

Just found out that sum decoders actually validate the message's checksum, now (in the commit done a few minutes ago) we are now re calculating the trailing NMEA0183 checksum (since the message is altered) 

1) Yes, this is tested and working on both MarineTraffic and AISHub. The motivation is initially done since AIS does not support AIVDO data and only AIVDM, and we would like (as a reporter) the ability to send through our own vessel details. You can see this live looking at AISHub for this station: https://www.aishub.net/stations/2254 (our converted MMSI is 512009734) and also you will see the same being sent to Marine Traffic too.

2) (pending) 

3) I think in reality this will be a good idea to have these options per endpoint as opposed to globally, the issue is, if we do this, it will break the configs for existing users (yet again) and lack backward compatibility. 

In reality, the two places anyone would ever send the AIS data is AISHub and Marine Traffic. Marine traffic doesn't seem to care if the vessel reported is on AIVDO or AIVDM they display it all the same as far as I am aware. While AISHub cant use AIVDO (Own vessel) data which means its ignored. In a perfect (sneaky) way I would go as far as saying this this conversation should happen automatically without even user knowledge

I can see you stumbled on this topic (you) raised 4 years back https://github.com/SignalK/aisreporter/issues/18 :) 

What do you think, should we make this as a user option (on or off by default?), or force all messages to convert without even user control?

**Comment by yifswery** [comment]
@hkapanen 

Just found out that sum decoders actually validate the message's checksum, now (in the commit done a few minutes ago) we are now re calculating the trailing NMEA0183 checksum (since the message is altered) 

1) Yes, this is tested and working on both MarineTraffic and AISHub. The motivation is initially done since AIS does not support AIVDO data and only AIVDM, and we would like (as a reporter) the ability to send through our own vessel details. You can see this live looking at AISHub for this station: https://www.aishub.net/stations/2254 (our converted MMSI is 512009734) and also you will see the same being sent to Marine Traffic too.

2) (pending) 

3) I think in reality this will be a good idea to have these options per endpoint as opposed to globally, the issue is, if we do this, it will break the configs for existing users (yet again) and lack backward compatibility. 

In reality, the two places anyone would ever send the AIS data is AISHub and Marine Traffic. Marine traffic doesn't seem to care if the vessel reported is on AIVDO or AIVDM they display it all the same as far as I am aware. While AISHub cant use AIVDO (Own vessel) data which means its ignored. In a perfect (sneaky) way I would go as far as saying this this conversation should happen automatically without even user knowledge

I can see you stumbled on this topic (you) raised 4 years back https://github.com/SignalK/aisreporter/issues/18 :) 

What do you think, should we make this as a user option (on or off by default?), or force all messages to convert without even user control?

**Comment by hkapanen** [comment]
@yifswery,

Good arguments for keeping existing configs and backward compatibility, so let's keep this as a global user option, default off. Nice catch on the checksum, thanks for the recalc code. Will push this out once the picture is updated.

**Comment by yifswery** [comment]
@hkapanen 

All done, Image updated in diff.

**Comment by hkapanen** [comment]
Many thanks @yifswery! How shall I credit you on the package contributors list?

**Comment by yifswery** [comment]
Thanks for megring!
Oh no need to add any credit. We're just stoked to use your plugin on our signalk set up!

**Pull request merged**
